# Generated by Django 4.2.1 on 2023-06-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=16)),
                ('email', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=16)),
                ('account_type', models.TextField(max_length=6)),
            ],
        ),
    ]
